import React from 'react'

import StaticView from '../View'

const Terms = () => (
  <span>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis blandit, nisl vitae auctor rhoncus, ligula ipsum suscipit augue, at tincidunt est augue in risus. Ut nibh enim, pulvinar vitae sapien vitae, cursus placerat magna. In consectetur fermentum nunc, vel porttitor dui volutpat vitae. Praesent quis est in ipsum tristique tempus. In convallis libero tristique varius pulvinar. Nunc placerat mi eget purus tristique, eu tempor quam blandit. Cras feugiat ligula nec interdum pharetra.</p>
    <p>Suspendisse pharetra, justo sit amet rutrum blandit, magna dui placerat urna, vitae interdum est libero vitae dui. Morbi eleifend accumsan odio et dictum. Vivamus vel lectus in risus eleifend facilisis. Donec a malesuada neque, non aliquet felis. Donec posuere neque a euismod eleifend. Curabitur egestas ultricies sagittis. Integer fermentum rhoncus turpis vel tempor.</p>
    <p>Nullam eu est vitae arcu tristique bibendum vehicula in est. Donec massa nunc, tristique in urna sed, condimentum rhoncus nunc. Vivamus vel accumsan ante. Etiam a viverra odio. In venenatis elit odio, non rutrum lacus fermentum eu. Fusce ex eros, volutpat quis commodo sit amet, commodo ut est. Nunc quis mi maximus neque venenatis tempor. Morbi placerat sed ex accumsan ornare. Pellentesque tristique nulla vel faucibus dapibus. Donec sagittis posuere semper. Donec faucibus mattis tempus. Vestibulum a volutpat quam.</p>
    <p>Duis cursus vel quam sed posuere. Donec eu facilisis odio. Nunc et ipsum euismod, malesuada est at, accumsan velit. Fusce in massa eget diam pharetra tristique nec in metus. Nullam magna urna, elementum eget auctor ut, fermentum ac purus. Nulla facilisi. Cras congue, neque quis dictum rhoncus, nibh metus venenatis enim, sit amet facilisis tortor sem eget urna. Nunc semper enim eget tortor faucibus, nec finibus nibh volutpat. Suspendisse fringilla nulla ut mattis commodo. Aliquam eget eros sed odio gravida ultrices. Aenean quis nisi feugiat elit mollis facilisis semper eu diam. Phasellus eleifend, enim eu venenatis finibus, lorem dui lobortis ipsum, et tristique dolor massa id dui. Maecenas pellentesque pulvinar aliquet. Integer maximus vehicula nisl, non commodo sem ornare nec. Ut feugiat ex at sagittis ornare. Ut semper dui id commodo euismod.</p>
    <p>Aenean mattis suscipit ante. Praesent metus mauris, euismod sed accumsan ac, cursus quis sapien. Pellentesque lacinia vestibulum quam vitae molestie. Fusce dictum iaculis nisi. Nunc at varius sem. Ut lobortis lorem venenatis tortor laoreet dictum. Nunc dapibus, tortor in egestas varius, ex tellus maximus tellus, id commodo dui mi egestas justo. Nullam a quam elit. Donec metus velit, gravida ut lacus tincidunt, interdum iaculis tellus. Donec tempus, dui sit amet dictum porttitor, purus urna placerat libero, et tincidunt purus enim eget lorem. Curabitur non volutpat massa. Morbi ultrices venenatis mauris, quis tempor est rhoncus in. Nullam nec erat non urna interdum pulvinar. Aliquam non nibh fringilla, egestas justo in, ultricies erat.</p>
  </span>
)

export default StaticView('Terms', Terms)
